/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IWyvernExchange,
  IWyvernExchangeInterface,
} from "../IWyvernExchange";

const _abi = [
  {
    inputs: [
      {
        internalType: "address[14]",
        name: "addrs",
        type: "address[14]",
      },
      {
        internalType: "uint256[18]",
        name: "uints",
        type: "uint256[18]",
      },
      {
        internalType: "uint8[8]",
        name: "feeMethodsSidesKindsHowToCalls",
        type: "uint8[8]",
      },
      {
        internalType: "bytes",
        name: "calldataBuy",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "calldataSell",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "replacementPatternBuy",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "replacementPatternSell",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "staticExtradataBuy",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "staticExtradataSell",
        type: "bytes",
      },
      {
        internalType: "uint8[2]",
        name: "vs",
        type: "uint8[2]",
      },
      {
        internalType: "bytes32[5]",
        name: "rssMetadata",
        type: "bytes32[5]",
      },
    ],
    name: "atomicMatch_",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IWyvernExchange__factory {
  static readonly abi = _abi;
  static createInterface(): IWyvernExchangeInterface {
    return new utils.Interface(_abi) as IWyvernExchangeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWyvernExchange {
    return new Contract(address, _abi, signerOrProvider) as IWyvernExchange;
  }
}
